accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name='index'),
    path("signup/", views.signup, name="signup"),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('editpw/', views.editpw, name='editpw'),
    path('delete/', views.delete, name='delete'),
    path('block_user/', views.block_user, name='block_user'),
    path('question/',views.question,name='quest'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:pk>/follow/', views.follow, name='follow'),
    path('<int:pk>/block', views.block, name='block'),
    path('<int:pk>/block_user_block', views.block_user_block, name='block_user_block'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    # path('<int:comment_pk>/reply/', views.reply, name='reply'),
    path('comments/<int:pk>/', views.comments_create, name='comments_create'),
    path('comments/delete/<int:article_pk>/<int:comment_pk>/', views.comments_delete, name='comments_delete'),
    path('recomments/<int:article_pk>/<int:comment_pk>/', views.recomments_create, name='recomments_create'),
    path('recomments/delete/<int:article_pk>/<int:recomment_pk>/', views.recomments_delete, name='recomments_delete'),
    path('like_article/<int:pk>/', views.like_article, name='like_article'),
    path('unlike_article/<int:pk>/', views.unlike_article, name='unlike_article'),
    path('search/', views.search, name='search'),
]

chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/send/", views.send, name="send"),
    path("<int:room_pk>/", views.detail, name="detail"),
    path("<int:pk>/first_send/", views.first_send, name="first_send"),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

semi_pjt_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
    path('products/', include('products.urls')),
    path('chats/', include('chats.urls')),
    path('service/', include('service_center.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_center/urls.py
from django.urls import path
from . import views

app_name="service_center"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('question/', views.question, name="question"),
    path('<int:service_pk>/', views.detail, name="detail"),
    path('<int:service_pk>/comments/',views.comment_create, name="comment_create"),
    path('<int:service_pk>/update', views.update, name="update"),
    path('admin_page/', views.admin_page, name="admin_page"),
    path('<int:service_pk>/<int:question_pk>/delete_comment/', views.delete_comment, name="delete_comment"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.


class User(AbstractUser):
    followings = models.ManyToManyField("self", symmetrical=False, related_name="followers")
    celsius = models.FloatField(default=36.5)
    blocking = models.ManyToManyField('self', symmetrical=False, related_name='blockers')
    secession = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now=True)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    introduce = models.TextField(blank=True)
    nickname = models.CharField(max_length=40, blank=True)
    image = models.ImageField(upload_to="profile/", blank=True)

articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models

from django.conf import settings

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    unlike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='unlike_articles')
    hitCount = models.IntegerField(default=0)
                            
class Comment(models.Model):
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE,  related_name='recomment', null=True)
    text = models.TextField(blank=True)

class Popularsearch(models.Model):
    terms = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    searchCount = models.IntegerField(default=1)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import check_password

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )
        
    def clean_username(self):
        username = self.cleaned_data['username']
        if get_user_model().objects.filter(username=username).exists():
            user = get_user_model().objects.get(username=username)
            if user.secession:
                raise ValidationError('탈퇴일로 부터 1년 동안 재가입은 불가능 합니다. 복구 문의시 고객센터 XXXX-XXXX 로 연락주시기 바랍니다.😢')
            return username
        return username


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "first_name",
            "last_name",
        )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            "introduce",
            "nickname",
            "image",
        )

class CheckPasswordForm(forms.Form):
    password = forms.CharField(widget = forms.PasswordInput(), label='')
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password
        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', '비밀번호가 달라요.')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth import get_user_model, login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm , PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def index(request):
    return render(request, 'accounts/index.html')

def signup(request):
    form = CustomUserCreationForm(request.POST or None)
    if form.is_valid():
        login(request, form.save())
        return redirect('articles:index')
    return render(request, 'accounts/signup.html', {'form': form})

def signin(request):
    form = AuthenticationForm() # 처음 들어오면 보이는 폼
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST) # 사용자가 입력한 내용
        if form.is_valid(): # 유효성 검사
            login(request, form.get_user())
            user = get_object_or_404(get_user_model(), pk=request.user.pk)
            if user.secession:
                logout(request)
                messages.error(request, '탈퇴 시 로그인은 불가능 합니다.😱')
                return redirect('accounts:login')
            return redirect('articles:index') # 통과하면 로그인 후에 articles/index로 리다이렉트
    context = {
        'form': form # 처음에 들어오면 method == 'GET' if문이 실행이 안되므로 18번째 줄 form을 반환,
                    # 만약 POST로 사용자가 입력한 내용이 유효성 검사를 통과 못하는 경우 20번째 줄 form을 반환
    }
    return render(request, 'accounts/login.html', context)

@login_required
def signout(request):
    logout(request)
    return redirect('articles:index')

def profile(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    return render(request, 'accounts/profile.html', {'user': user})

@login_required
def follow(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if user != request.user:
        if user.followers.filter(pk=request.user.pk).exists():
            user.followers.remove(request.user)
            user.celsius -= 0.2
            user.celsius = round(user.celsius, 1)
            user.save()
        else:
            user.followers.add(request.user)
            user.celsius += 0.2
            user.celsius = round(user.celsius, 1)
            user.save()
    return redirect('accounts:profile', user.username)

@login_required
def edit(request):
    if request.method == "POST":
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_change_form.is_valid():
            user = user_change_form.save()
            profile_form.save()
            return redirect("accounts:profile", user.username)
        return redirect("accounts:edit")
    user_change_form = CustomUserChangeForm(instance=request.user)
    pro, create = Profile.objects.get_or_create(user=request.user)
    profile_form = ProfileForm(instance=pro)
    context = {
        "user_change_form": user_change_form,
        "profile_form": profile_form,
    }
    return render(request, "accounts/edit.html", context)

@login_required
def editpw(request):
    form = PasswordChangeForm(request.user) # 처음 들어오면 보이는 폼
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST) # 사용자가 입력한 내용
        if form.is_valid(): # 유효성 검사
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index') # 통과하면 로그인 후에 리다이렉트
    context = {
        'form': form # 처음에 들어오면 method == 'GET' if문이 실행이 안되므로 18번째 줄 form을 반환,
                    # 만약 POST로 사용자가 입력한 내용이 유효성 검사를 통과 못하는 경우 20번째 줄 form을 반환
    }
    return render(request, 'accounts/editpw.html', context)

@login_required
def delete(request):
    form = CheckPasswordForm(request.user)
    if request.method == 'POST':
        form = CheckPasswordForm(request.user, request.POST)
        if form.is_valid():
            user = get_object_or_404(get_user_model(), pk=request.user.pk)
            user.secession = True
            user.save()
            logout(request)
            return redirect('articles:index')
    context = {
        'form': form,
    }
    return render(request, 'accounts/delete.html', context)

def question(request):
    return render(request, 'accounts/question.html')

@login_required
def block(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if user != request.user:
        if user.blockers.filter(pk=request.user.pk).exists():
            user.blockers.remove(request.user)
            user.celsius += 1
            user.celsius = round(user.celsius, 1)
            user.save()
        else:
            user.blockers.add(request.user)
            user.celsius -= 1
            user.celsius = round(user.celsius, 1)
            user.save()
    return redirect('accounts:profile', user.username)

@login_required
def block_user(request):
    block_users = request.user.blocking.all()
    return render(request, 'accounts/block_user.html', {'block_users': block_users})

@login_required
def block_user_block(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if user != request.user:
        if user.blockers.filter(pk=request.user.pk).exists():
            user.blockers.remove(request.user)
            user.celsius += 1
            user.celsius = round(user.celsius, 1)
            user.save()
        else:
            user.blockers.add(request.user)
            user.celsius -= 1
            user.celsius = round(user.celsius, 1)
            user.save()
    return redirect('accounts:block_user')

accounts/templates/accounts/block_user.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<div class="container">

    {% for block_user in block_users %}
    <div class="card m-4 p-2">
        <div class="d-flex justify-content-center">


            {% if block_user.profile.image %}
            <img src="{{block_user.profile.image.url}}" class="rounded-circle" alt="" style="height: 100px; width:100px;"> {% else %}
            <img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 100px; width:100px;"> {% endif %}


            <p class="align-self-center pt-3 ms-4"><a class="navbar-brand ms-4" href="{% url 'accounts:profile' block_user.username %} ">{{ block_user.username }}</a></p>
            <a class="ms-5 align-self-center text-decoration-none text-black fw-bold" href="{% url 'accounts:block_user_block' block_user.pk %}">차단 취소</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

accounts/templates/accounts/delete.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<p class="mx-2">탈퇴 즉시 회원 정보가 영구 삭제되며 복구할 수 없습니다. 그래도 진행하시려면 비밀번호를 입력해주시기 바랍니다.</p>
<form action="" method="POST">
    {% csrf_token %} {% bootstrap_form form %}
    <div class="d-flex justify-content-end">{% bootstrap_button button_type='submit' content='탈퇴' button_class="btn btn-danger"%}</div>
</form>
{% endblock content %}

accounts/templates/accounts/edit.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form user_change_form %} {% bootstrap_form profile_form %} {% bootstrap_button button_type='submit' content='수정' %}
</form>
{% endblock content %}

accounts/templates/accounts/editpw.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<form action="" method="POST">
    {% csrf_token %} {% bootstrap_form form %} {% bootstrap_button button_type='submit' content='비밀번호 변경' %}
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %} {% for message in messages %}
<div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button> {{ message }}
</div>
{% endfor %}
<h1>로그인</h1>
<form action="" method="POST">

    {% csrf_token %} {% bootstrap_form form %}
    <div class="d-flex justify-content-start">{% bootstrap_button button_type='submit' content='로그인' %}

        <a href="{% url 'accounts:signup' %}" class="btn btn-primary ms-2">회원가입</a>
    </div>
</form>
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    window.setTimeout(function() {
        $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function() {
            $(this).remove();
        });
    }, 1500);
</script>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<div class="card text-center mt-5">
    <div class="card-header">
        {{user.username}}의 프로필
    </div>
    <div class="card-body">
        <!-- <h5 class="card-title">{{user.username}}의 프로필</h5> -->
        {% if user.profile.image %}
        <img src="{{user.profile.image.url}}" class="rounded-circle" alt="" style="height: 100px; width:100px;"> {% else %}
        <img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 100px; width:100px;"> {% endif %}
        <p class="card-text"></p>
        <p class="card-text">{{user.first_name}} {{user.last_name}}</p>
        <p class="card-text">매너온도 | {{user.celsius}}℃ {% if user.celsius < 36.5 %}<i class="bi bi-emoji-frown text-danger"></i>{% elif user.celsius == 36.5 %}<i class="bi bi-emoji-neutral"></i>{% else %}<i class="bi bi-emoji-smile text-primary"></i>{% endif %}</p>
        <p class="card-text">introduce | {{user.profile.introduce}}</p>
        <p class="card-text">nickname | {{user.profile.nickname}}</p>
        <p class="card-text">email | {{user.email}}</p>
        {% if request.user == user %}
        <a href="{% url 'accounts:edit' %}" class="btn btn-outline-dark">수정</a>
        <a href="{% url 'accounts:editpw' %}" class="btn btn-outline-dark">비밀번호 변경</a>
        <a href="{% url 'accounts:delete' %}" class="btn btn-outline-dark">탈퇴</a>
        <a href="{% url 'accounts:block_user' %}" class="btn btn-outline-dark">차단 목록</a>
        {% if request.user.is_superuser %}
        <a href="{% url 'service_center:admin_page' %}" class="btn btn-outline-dark">문의 내역</a>
        {% else %}
        <a href="{% url 'service_center:index' %}" class="btn btn-outline-dark">내 문의</a>
        {% endif %}
        {% endif %}
    </div>
    <div class="card-footer text-muted">
        팔로잉 수 | {{user.followings.count}} / 팔로워 수 | {{user.followers.count}}
    </div>
    {% if request.user == user %} {% else %}
    <div class="d-flex justify-content-center">
        <a href="{% url 'chats:first_send' user.pk %}" class="btn btn-outline-dark">DM</a>
        <a href="{% url 'accounts:follow' user.pk %}" class="text-decoration-none">
        {% if request.user in user.followers.all %}
    <button class="btn btn-outline-dark m-2 me-0" type="button">
        팔로우 취소
    </button>
{% else %}
    <button class="btn btn-outline-dark m-2 me-0" type="button">
        팔로우
    </button>
</a> {% endif %}
<a href="{% url 'accounts:block' user.pk %}" class="text-decoration-none">
    {% if request.user in user.blockers.all %}
<button class="btn btn-outline-dark m-2" type="button">
    차단 취소
</button>
{% else %}
<button class="btn btn-outline-dark m-2" type="button">
    차단
</button>
</a> {% endif %}
{% endif %}
    </div>
</div>


{%for article in user.article_set.all %}
<div class="container">
    <p>
        <div class="card border-dark mb-3 test" style="max-width: 18rem; display: contents;">
            <div class="card-header">{{forloop.counter}}</div>
            <div class="card-body text-dark">
                <h5 class="card-title"><a class="text-decoration-none" href="{% url 'articles:detail' article.pk %}">{{article.title}}</a></h5>
            </div>
        </div>
    </p>
</div>
{% endfor %}{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}

<h1>회원가입</h1>
<div class="container">

    <form action="" method="POST">
        {% csrf_token %} {% bootstrap_form form %} {% bootstrap_button button_type='submit' content='회원가입' %}
    </form>
</div>

{% endblock content %}