accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name='index'),
    path("signup/", views.signup, name="signup"),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('editpw/', views.editpw, name='editpw'),
    path('delete/', views.delete, name='delete'),
    path('block_user/', views.block_user, name='block_user'),
    path('question/',views.question,name='quest'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:pk>/follow/', views.follow, name='follow'),
    path('<int:pk>/block', views.block, name='block'),
    path('<int:pk>/block_user_block', views.block_user_block, name='block_user_block'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    # path('<int:comment_pk>/reply/', views.reply, name='reply'),
    path('comments/<int:pk>/', views.comments_create, name='comments_create'),
    path('comments/delete/<int:article_pk>/<int:comment_pk>/', views.comments_delete, name='comments_delete'),
    path('recomments/<int:article_pk>/<int:comment_pk>/', views.recomments_create, name='recomments_create'),
    path('recomments/delete/<int:article_pk>/<int:recomment_pk>/', views.recomments_delete, name='recomments_delete'),
    path('like_article/<int:pk>/', views.like_article, name='like_article'),
    path('unlike_article/<int:pk>/', views.unlike_article, name='unlike_article'),
    path('search/', views.search, name='search'),
]

chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/send/", views.send, name="send"),
    path("<int:room_pk>/", views.detail, name="detail"),
    path("<int:pk>/first_send/", views.first_send, name="first_send"),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

semi_pjt_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
    path('products/', include('products.urls')),
    path('chats/', include('chats.urls')),
    path('service/', include('service_center.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models

from django.conf import settings

class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    unlike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='unlike_articles')
    hitCount = models.IntegerField(default=0)
                            
class Comment(models.Model):
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE,  related_name='recomment', null=True)
    text = models.TextField(blank=True)

class Popularsearch(models.Model):
    terms = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    searchCount = models.IntegerField(default=1)

articles/forms.py
from django import forms
from .models import Article, Comment
from django.forms import TextInput
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'image',)
        labels = {
            'title': '제목',
            'content': '내용',
            'image': '이미지 업로드',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content': '',
        }
        widgets = {
            'content': TextInput(attrs={
                'placeholder': '댓글 내용을 입력해 주세요.',
            })
        }

class ReCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content': '',
        }
        widgets = {
            'content': TextInput(attrs={
                'placeholder': '답글 내용을 입력해 주세요.',
            })
        }

articles/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import Article, Comment, Popularsearch
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.auth import get_user_model
# Create your views here.
@login_required
def index(request):
    articles = Article.objects.order_by('-pk')
    search_all = Popularsearch.objects.order_by('-searchCount')[:3]

    context = {
        'articles' : articles,
        'search_all': search_all,
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == "POST":
        article_form = ArticleForm(request.POST, request.FILES)
        user = get_user_model().objects.get(pk=request.user.pk)
        if user.celsius < 30:
            messages.error(request, '온도가 너무 낮아서 글을 작성할 수 없어요.😡')
            return render(request, 'articles/create.html', {'article_form': article_form})
        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect(request.GET.get("next") or 'articles:index')
    else:
        article_form = ArticleForm()

    context = {
        'article_form' : article_form
    }

    return render(request, 'articles/create.html', context)

@login_required
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    recomment_form = ReCommentForm()
    article.hitCount += 1
    article.save()
    comments = article.comment_set.filter(parent_comment=None)

    context = {
        'article' : article,
        'comment_form' : comment_form,
        'comments' : comments, #애초에 Null 값 제거
        'recomment_form' : recomment_form,
        'hitCount': article.hitCount,
    }
   
    return render(request, 'articles/detail.html', context)

@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)

    if request.user == article.user:
        if request.method == 'POST':
            article_form = ArticleForm(request.POST, request.FILES, instance=article)

            if article_form.is_valid():
                article_form.save()
                return redirect("articles:detail", article.pk)
        else:
            article_form = ArticleForm(instance=article)
        context = {
            'article_form': article_form
        }
        return render(request, 'articles/update.html', context)

    else:
        messages.warning(request, '작성자만 수정할 수 있습니다.')
        return redirect('articles:detail', article.pk)

@login_required
def delete(request, pk):
    Article.objects.get(id=pk).delete()
    return redirect('articles:index')


dic = {'0':'zero', '1':'one', '2':'two', '3':'three', '4':'four', '5':'five', '6':'six', '7':'seven', '8':'eight', '9':'nine'}
# 댓글
@login_required
def comments_create(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
            temp = ''
            for i in str(comment.pk):
                temp += dic[i]
            comment.text = temp
            comment.save()
            return redirect('articles:detail', article.pk)

@login_required
def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', article_pk)

# 대댓글
@login_required
def recomments_create(request, article_pk, comment_pk):
    # 현재 article 저장
    article = Article.objects.get(pk=article_pk)

    if request.method == "POST":
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            recomment = comment_form.save(commit=False)
            recomment.article = article
            recomment.user = request.user
            recomment.parent_comment_id = comment_pk
            temp = ''
            for i in str(comment_pk):
                temp += dic[i]
            recomment.text = temp
            recomment.save()

            return redirect('articles:detail', article.pk)

@login_required
def recomments_delete(request, article_pk, recomment_pk):
    recomment = Comment.objects.get(pk=recomment_pk)
    recomment.delete()
    return redirect('articles:detail', article_pk)

# # 대댓글 출력
# def reply(request, comment_pk):
#     temp = Comment.objects.filter(parent_comment_id=comment_pk)
#     arr = []
#     for i in temp:
#         arr.append((i.user.username, i.content))
#     return JsonResponse({'content': arr})

# 좋아요
@login_required
def like_article(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
        user = article.user
        user.celsius -= 0.1
        user.celsius = round(user.celsius, 1)
        user.save()
    else:
        article.like_users.add(request.user)
        user = article.user
        user.celsius += 0.1
        user.celsius = round(user.celsius, 1)
        user.save()
    return redirect('articles:detail', pk)

# 싫어요
@login_required
def unlike_article(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user in article.unlike_users.all():
        article.unlike_users.remove(request.user)
        user = article.user
        user.celsius += 0.1
        user.celsius = round(user.celsius, 1)
        user.save()
    else:
        article.unlike_users.add(request.user)
        user = article.user
        user.celsius -= 0.1
        user.celsius = round(user.celsius, 1)
        user.save()
    return redirect('articles:detail', pk)


# 검색 기능 + 검색어 저장
def search(request):
    search = request.GET.get("search")
    search_found = Popularsearch.objects.filter(terms=search)
    search_all = Popularsearch.objects.order_by('-searchCount')[:3]

    if search:
        # index에 검색 결과 뿌려주는 쿼리셋 저장
        search_result = Article.objects.filter(title__contains=search)
    
    # 사용자로부터 입력받은 검색어가 이미 있다면 searchCount += 1
    if search_found:
        search_exist = Popularsearch.objects.get(terms=search)
        search_exist.searchCount += 1
        search_exist.save()
    else:
        # 사용자로부터 입력받은 검색어를 DB에 저장
        Popularsearch.objects.create(terms=search)

    context = {
        'search_result': search_result,
        'search_all': search_all,
        'search': search,
    }
    return render(request, 'articles/index.html', context)

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form article_form %}
    <input class='btn btn-outline-primary' type='submit' value='작성'>
    <a class='btn btn-outline-danger' href="{% url 'articles:index' %}">취소</a>
</form>
<script>
    window.setTimeout(function() {
    $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
    });
}, 1500);
</script>

{% endblock %}

articles/templates/articles/detail.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% load static %} {% block content %}
<!-- 글 제목, 글 번호, 작성일자, 작성자 -->
<h2 class="mb-3">[No.{{ article.pk }}] {{ article.title }}</h2>
<p>
    <div>
        <span>
      {% if article.user.profile.image %}
        <a href="{% url 'accounts:profile' article.user.username %}" style="text-decoration:none" class="text-dark"><img src="{{ article.user.profile.image.url}}" class="rounded-circle" alt="" style="height: 70px; width:70px;"></a>
      {% else %}
        <a href="{% url 'accounts:profile' article.user.username %}" style="text-decoration:none" class="text-dark"><img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 70px; width:70px;"></a>
      {% endif %}
    </span>
        <span>
      <span class="fw-bold ms-2">
        <a href="{% url 'accounts:profile' article.user.username %}" style="text-decoration:none" class="text-dark">{{ article.user.username }} 매너온도 {{ article.user.celsius}}℃{% if article.user.celsius < 36.5 %}<i class="bi bi-emoji-frown text-danger"></i>{% elif article.user.celsius == 36.5 %}<i class="bi bi-emoji-neutral"></i>{% else %}<i class="bi bi-emoji-smile text-primary"></i>{% endif %}</a>
      </span>
        <div>
            <span class="text-muted">{{ article.updated_at }}</span>
            <span class="fw-bold ms-2 text-muted">조회 {{ article.hitCount }}</span>
        </div>
        </span>
    </div>
</p>


<hr>
<!-- 이미지 -->
{% if article.image %}
<img src="{{ article.image.url }}" alt="{{ article.image }}" style="max-width: 500px; max-height: 500px;"> {% endif %}

<!-- 글 내용 -->
<p class="mt-3">{{ article.content }}</p>
<span>
  <a href="{% url 'articles:like_article' article.pk %}" style="text-decoration:none">
  {% if request.user in article.like_users.all %}
  <i class="bi bi-heart-fill text-danger"></i>
  {% else %}
  <i class="bi bi-heart text-danger"></i>
  {% endif %}
  </a> <span>{{ article.like_users.count }}명이 이 글을 좋아해요</span>
</span>
<span>
  <a href="{% url 'articles:unlike_article' article.pk %}" style="text-decoration:none">
  {% if request.user in article.unlike_users.all %}
  <i class="bi bi-emoji-frown-fill text-danger"></i>
  {% else %}
  <i class="bi bi-emoji-frown text-danger"></i>
  {% endif %}
  </a> <span>{{ article.unlike_users.count }}명이 이 글을 싫어해요</span>
</span>
<hr>

<!-- 댓글 -->
<!-- 작성된 댓글 보여주기 -->
<form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}{% bootstrap_form comment_form%}
    <div class="d-flex justify-content-end mb-2">
        {% bootstrap_button button_type='submit' content='댓글 작성' %}
    </div>

</form>
<p class="fw-bold">[총 {{comments.count}}개 댓글]</p>
<div class="mb-3">
    {% for comment in comments %}
    <div>
        {% if comment.user.profile.image %}
        <a href="{% url 'accounts:profile' comment.user.username %}" style="text-decoration:none" class="text-dark"><img src="{{ comment.user.profile.image.url}}" class="rounded-circle" alt="" style="height: 40px; width:40px;"></a>
        {% else %}
        <a href="{% url 'accounts:profile' comment.user.username %}" style="text-decoration:none" class="text-dark"><img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 40px; width:40px;"></a>
        {% endif %}
        <a href="{% url 'accounts:profile' comment.user.username %}" style="text-decoration:none" class="text-dark">{{ comment.user.username }}</a>
    </div>
    <div>
        {{ comment.content }}
    </div>
    <div class="d-flex">
        <div class="accordion accordion-flush" id="{{comment.text}}">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne{{comment.text}}{{comment.text}}" aria-expanded="false" aria-controls="flush-collapseOne{{comment.text}}{{comment.text}}">
            답글 쓰기
          </button>
                </h2>
                <div id="flush-collapseOne{{comment.text}}{{comment.text}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#{{comment.text}}">
                    <div class="accordion-body">
                        <form action="{% url 'articles:recomments_create' article.pk comment.pk %}" method="POST">
                            {% csrf_token %}
                            <div class="d-flex">
                                <div style="width: 300px;">
                                    {% bootstrap_form recomment_form %}
                                </div>
                                <div class="mx-2">
                                    {% bootstrap_button button_type='submit' content='답글 작성' %}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="accordion accordion-flush" id="{{comment.text}}">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne2">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne{{comment.text}}" aria-expanded="false" aria-controls="flush-collapseOne{{comment.text}}">
            답글 확인 {{comment.recomment.count}} 개
          </button>
                </h2>
                <div id="flush-collapseOne{{comment.text}}" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#{{comment.text}}">
                    <div class="accordion-body">
                        {% for recom in comment.recomment.all %}
                        <div>
                            {% if recom.user.profile.image %}
                            <a href="{% url 'accounts:profile' recom.user.username %}" style="text-decoration:none" class="text-dark"><img src="{{ recom.user.profile.image.url}}" class="rounded-circle" alt="" style="height: 40px; width:40px;"></a>
                            {% else %}
                            <a href="{% url 'accounts:profile' recom.user.username %}" style="text-decoration:none" class="text-dark"><img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 40px; width:40px;"></a>
                            {% endif %}
                            <a href="{% url 'accounts:profile' recom.user.username %}" style="text-decoration:none" class="text-dark">{{ recom.user.username }}</a>
                        </div>
                        <div>
                            {{ recom.content }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- 글 수정/삭제 버튼 및 목록으로 돌아가기 버튼 -->
{% if request.user == article.user %}
<p>
    <a href="{% url 'articles:update' article.pk %}" class="btn btn-primary">수정하기</a>
    <a href="{% url 'articles:delete' article.pk %}" class="btn btn-primary">삭제하기</a>
</p>
{% endif %}
<p>
    <a href="{% url 'articles:index' %}" class="btn btn-primary mt-2">목록으로</a>
</p>
</div>
{% comment %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/article.js' %}"></script> {% endcomment %} {% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %} {% load static %} {% load django_bootstrap5 %} {% block search %}
<form action="{% url 'articles:search' %}" class="d-flex" role="search" style="height:40px;">
    <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit" style="height:40px; width:80px;">검색</button>
</form>
{% endblock %} {% block content %}
<!-- 배너 캐러셀 -->
<div id="carouselExampleControls" class="carousel slide mt-3" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="../../../static/images/중고의집배너1.png" class="d-block w-100" alt="dummy-image1">
        </div>
        <div class="carousel-item">
            <img src="../../../static/images/중고의집배너2.png" class="d-block w-100" alt="dummy-image2">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
</div>

<!-- 커뮤니티 이름 -->
<h3 class="mt-5 fw-bold text-center text-warning">지역 커뮤니티</h3>

<!-- 인기검색어 -->
{% if search %}

<div class="block">
    <ul id="ticker">
        {% for search in search_all %}
        <a href="?search={{ search.terms }}" class="text-decoration-none text-black"><li class="text-center" ><span class="fw-bold">현재 인기 검색어 [{{ forloop.counter }}위]</span> {{ search.terms }} </li></a>
        {% endfor %}
    </ul>
</div>
{% else %}
<div class="block">
    <ul id="ticker">
        {% for search in search_all %}
        <a href="search/?search={{ search.terms }}" class="text-decoration-none text-black"><li class="text-center" ><span class="fw-bold">현재 인기 검색어 [{{ forloop.counter }}위]</span> {{ search.terms }} </li></a>
        {% endfor %}
    </ul>
</div>
{% endif %}
<!-- 커뮤니티 글쓰기 -->
<div class='text-end mt-3'>
    <a class='btn btn-warning btn-sm fw-bold' href="{% url 'articles:create' %}">글쓰기 <i class="bi bi-pencil"></i></a>
</div>

<!-- 검색어 입력 시 검색어에 맞는 글만 출력 -->
{% if search_result %} {% for search in search_result %} {% if search.user not in request.user.blocking.all %}
<div class="row d-flex justify-content-between">
    <div class="card col-6 my-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                {% if search.image %}
                <a href="{% url 'articles:detail' search.pk %}"><img src="{{ search.image.url }}" alt="{{ search.image }}" class="card-img-top" style="height: 151px;"></a>
                {% else %}
                <a href="{% url 'articles:detail' search.pk %}"><img src="{% static './images/hmm.png' %}" class="card-img-top" style="height: 151px;"></a>
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">
                        <h5><span class="fw-bold"><a href="{% url 'articles:detail' search.pk %}" style="text-decoration:none" class="text-dark">[No.{{ forloop.revcounter }}] </span>{{ search.title }}</a>
                        </h5>
                    </h5>
                    <p class="card-text fw-lighter text-muted">
                        <span class="mt-3">
                  {% if search.user.profile.image %}
                  <a class="text-dark" href="{% url 'accounts:profile' search.user.username %}" style="text-decoration:none" class="text-dark">
                    <img src="{{ search.user.profile.image.url}}" class="rounded-circle" alt="" style="height: 40px; width:40px;">
                  </a>
                  {% else %}
                  <a class="text-dark" href="{% url 'accounts:profile' search.user.username %}" style="text-decoration:none">
                    <img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 40px; width:40px;">
                  </a>
                  {% endif %}
                </span><a href="{% url 'accounts:profile' search.user.username %}" style="text-decoration:none" class="text-dark">{{ search.user.username }}</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %} {% endfor %}

<!-- 모든 글 출력 -->
{% else %}
<div class="row d-flex justify-content-between">
    {% for article in articles %} {% if article.user not in request.user.blocking.all %}
    <div class="card col-6 my-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                {% if article.image %}
                <a href="{% url 'articles:detail' article.pk %}"><img src="{{ article.image.url }}" alt="{{ article.image }}" class="card-img-top" style="height: 151px;"></a>
                {% else %}
                <a href="{% url 'articles:detail' article.pk %}"><img src="{% static './images/hmm.png' %}" class="card-img-top" style="height: 151px;"></a>
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">
                        <h5><span class="fw-bold"><a href="{% url 'articles:detail' article.pk %}" style="text-decoration:none" class="text-dark">[No.{{ forloop.revcounter }}] </span>{{ article.title }}</a>
                        </h5>
                    </h5>
                    <p class="card-text fw-lighter text-muted">
                        <span class="mt-3">
              {% if article.user.profile.image %}
              <a class="text-dark" href="{% url 'accounts:profile' article.user.username %}" style="text-decoration:none" class="text-dark">
                <img src="{{ article.user.profile.image.url}}" class="rounded-circle" alt="" style="height: 40px; width:40px;">
              </a>
              {% else %}
              <a class="text-dark" href="{% url 'accounts:profile' article.user.username %}" style="text-decoration:none">
                <img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 40px; width:40px;">
              </a>
              {% endif %}
            </span><a href="{% url 'accounts:profile' article.user.username %}" style="text-decoration:none" class="text-dark">{{ article.user.username }}</a></p>
                </div>
            </div>
        </div>
    </div>
    {% endif %} {% endfor %}
</div>

{% endif %}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script type='text/javascript'src="{% static 'js/search_view.js' %}"></script>
<link rel="stylesheet" href="{% static './css/search_view.css' %}"> {% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

<p>articles/update</p>

<form action="" method="POST" enctype="multipart/form-data">

  {% csrf_token %}
  {% bootstrap_form article_form %}
  <input type='submit' value='제출'>
  
</form>

{% endblock %}