accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name='index'),
    path("signup/", views.signup, name="signup"),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('editpw/', views.editpw, name='editpw'),
    path('delete/', views.delete, name='delete'),
    path('block_user/', views.block_user, name='block_user'),
    path('question/',views.question,name='quest'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:pk>/follow/', views.follow, name='follow'),
    path('<int:pk>/block', views.block, name='block'),
    path('<int:pk>/block_user_block', views.block_user_block, name='block_user_block'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    # path('<int:comment_pk>/reply/', views.reply, name='reply'),
    path('comments/<int:pk>/', views.comments_create, name='comments_create'),
    path('comments/delete/<int:article_pk>/<int:comment_pk>/', views.comments_delete, name='comments_delete'),
    path('recomments/<int:article_pk>/<int:comment_pk>/', views.recomments_create, name='recomments_create'),
    path('recomments/delete/<int:article_pk>/<int:recomment_pk>/', views.recomments_delete, name='recomments_delete'),
    path('like_article/<int:pk>/', views.like_article, name='like_article'),
    path('unlike_article/<int:pk>/', views.unlike_article, name='unlike_article'),
    path('search/', views.search, name='search'),
]

chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/send/", views.send, name="send"),
    path("<int:room_pk>/", views.detail, name="detail"),
    path("<int:pk>/first_send/", views.first_send, name="first_send"),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:products_pk>/', views.detail, name="detail"),
    path('<int:products_pk>/update/', views.update, name="update"),
    path('<int:products_pk>/delete/', views.delete, name="delete"),
    path('<int:products_pk>/zzim', views.zzi, name='zzi'),
    path('<int:products_pk>/sold_out/', views.sold_out, name='sold_out'),
    path('search/', views.search, name='search'),
]

semi_pjt_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
    path('products/', include('products.urls')),
    path('chats/', include('chats.urls')),
    path('service/', include('service_center.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" style="height:100%;">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>중고의 집</title>

    <!-- bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <!-- bootstrap Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>

    <!-- bootstrap icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>

</head>

<body style="height: 100%;">

    <div class="container" style="min-height: 100%;position:relative;">
        <!-- navBar -->

        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">

                <!-- 중고의집 로고 -->
                <a class="navbar-brand text-success" href="{% url 'articles:index' %}" style="text-decoration:none;">
                    <a href="{% url 'articles:index' %}" style="text-decoration:none;" class="text-dark fw-bold"><img src="{% static './images/logo.png' %}" style="width:5rem; height:5rem;"></a>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

                <!-- 지역 커뮤니티, 중고거래 게시판, 검색 -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-dark ms-2 fw-bold" aria-current="page" href="{% url 'articles:index' %}" style="text-decoration:none;">지역 커뮤니티</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" href="{% url 'products:index' %}" style="text-decoration:none;">중고거래</a>
                        </li>
                    </ul>
                    {% block search %} {% endblock %}
                    <a class='btn btn-dark ms-2' href="{% url 'chats:index' %}">채팅하기</a>


                </div>
                <a class="navbar-brand " href="{% url 'articles:index' %} "></a>
                {% else %}
                <a class="navbar-brand " href="{% url 'accounts:login' %} "></a>
                <span>방문해주셔서 감사합니다! 서비스를 이용하시려면 <a href="{% url 'accounts:signup' %} ">회원가입</a> 또는 <a href="{% url 'accounts:login' %} ">로그인</a>을 해주세요. 😎</span> {% endif %}

            </div>
        </nav>


        {% if request.user.is_authenticated %}
        <div class="mt-2 mb-2">
            <span>
                <a class="navbar-brand ms-4" href="{% url 'accounts:profile' request.user.username %} ">{{request.user}}</a>님, 로그인을 환영합니다. 어서오세요!
            </span>

            <span class="float-end">
                <!-- <a class="btn btn-outline-success" href="" style="text-decoration:none;" role="button">
                  <i class="bi bi-box-arrow-right"></i>내 프로필</a> -->
                <a class="btn btn-outline-danger mx-4" href="{% url 'accounts:logout' %}" style="text-decoration:none;" role="button">
                  <i class="bi bi-box-arrow-right"></i>로그아웃</a>
            </span>
        </div>
        {% endif %}

        <!-- extends block-->
        {% block content %} {% endblock content %}
    </div>

    <footer class="bg-light position-relative bottom-0" style="height:200px; bottom: 0;">
        <div class="container">
            <p class="pt-5">팀원 | 김재형 김현정 노가빈 이용환</p>
            <p>Copyright © 2022 used article deal.co.,Ltd. All rights reserved. Contact webmaster for more information. | <span class="fw-bold"><a href="{% url 'accounts:quest' %}" class="text-decoration-none text-black">자주 묻는 질문</a></span></p>
        </div>


    </footer>


</body>

</html>