accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name='index'),
    path("signup/", views.signup, name="signup"),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('editpw/', views.editpw, name='editpw'),
    path('delete/', views.delete, name='delete'),
    path('block_user/', views.block_user, name='block_user'),
    path('question/',views.question,name='quest'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:pk>/follow/', views.follow, name='follow'),
    path('<int:pk>/block', views.block, name='block'),
    path('<int:pk>/block_user_block', views.block_user_block, name='block_user_block'),
]

chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/send/", views.send, name="send"),
    path("<int:room_pk>/", views.detail, name="detail"),
    path("<int:pk>/first_send/", views.first_send, name="first_send"),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:products_pk>/', views.detail, name="detail"),
    path('<int:products_pk>/update/', views.update, name="update"),
    path('<int:products_pk>/delete/', views.delete, name="delete"),
    path('<int:products_pk>/zzim', views.zzi, name='zzi'),
    path('<int:products_pk>/sold_out/', views.sold_out, name='sold_out'),
    path('search/', views.search, name='search'),
]

semi_pjt_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls')),
    path('products/', include('products.urls')),
    path('chats/', include('chats.urls')),
    path('service/', include('service_center.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from django.conf import settings
# Create your models here.

class Products(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()
    # ImageSpecField : 원본 ImageField로부터 생성(원본o, 썸네일o)
    original_image = models.ImageField(upload_to='photos')
    formatted_image = ImageSpecField(
        source='original_image',
        processors=[ResizeToFill(200,200)],
        format='JPEG',
        options={'quality':100}
    )
    price = models.IntegerField()
    hit = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    zzim = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='zzim_pro')
    sold = models.BooleanField(default=False)
    
class Location(models.Model):
    trade_locationx = models.CharField(max_length=100)
    trade_locationy = models.CharField(max_length=100)
    product = models.OneToOneField(Products, on_delete=models.CASCADE)

class Popularsearch(models.Model):
    terms = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    searchCount = models.IntegerField(default=1)

products/forms.py
from django import forms
from .models import Products, Location

class ProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = (
            'title',
            'content',
            'original_image',
            'price',
        )

        labels = {
            "title": "제목",
            "content":"내용",
            "original_image":"이미지",
            "price" : "가격(원)",
        }
class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = (
            'trade_locationx',
            'trade_locationy',
        )

products/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Products, Popularsearch
from .forms import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.contrib import messages
# Create your views here.

def index(request):
    products = Products.objects.order_by('-pk')
    search_all = Popularsearch.objects.order_by('-searchCount')[:3]
    context = {
        'products':products,
        'search_all': search_all,
    }
    return render(request, 'products/index.html', context)

@login_required
def create(request):
    productform = ProductsForm()
    locationform = LocationForm()
    if request.method == "POST":
        productform = ProductsForm(request.POST, request.FILES)
        locationform = LocationForm(request.POST)
        user = get_user_model().objects.get(pk=request.user.pk)
        if user.celsius < 30:
            context = {
                'productform':productform,
                'locationform':locationform,
            }
            messages.error(request, '온도가 너무 낮아서 글을 작성할 수 없어요.😡')
            return render(request, 'products/form.html', context)
        if productform.is_valid() and locationform.is_valid(): # 유효성 검사
            # 로그인한 유저만 글 작성가능해서
            products = productform.save(commit=False)
            products.user = request.user
            products.save()
            location = locationform.save(commit=False)
            location.product = products
            location.save()
            # 일단 임의로 redirect
            return redirect('products:index')
    context = {
        'productform':productform,
        'locationform':locationform,
    }
    return render(request, 'products/form.html', context)

def detail(request, products_pk):
    products = get_object_or_404(Products, pk=products_pk)
    location = get_object_or_404(Location, product_id=products_pk)
    products.hit += 1
    products.save()
    context = {
        'products':products,
        'location':location,
    }
    return render(request,'products/detail.html', context)

@login_required
def update(request, products_pk):
    products = get_object_or_404(Products, pk=products_pk)
    loca = get_object_or_404(Location, product_id=products_pk)
    # 로그인한 유저와 작성한 유저가 같다면
    if request.user == products.user:
        if request.method == "POST":
            form = ProductsForm(request.POST, request.FILES, instance=products)
            locationform = LocationForm(request.POST, instance=loca)
            if form.is_valid():
                # 로그인 구현을 아직 안해서
                form.save()
                locationform.save()
                return redirect('products:detail', products.pk)
        else:
            form = ProductsForm(instance=products)
            locationform = LocationForm(instance=loca)
        context = {
            'productform':form,
            'locationform' : locationform,
        }
        return render(request, 'products/form.html', context)
    # 작성자가 아닐 때
    else:
        return redirect('products:detail', products.pk)

@login_required
def delete(request, products_pk):
    products = get_object_or_404(Products, pk=products_pk)
    products.delete()
    return redirect('products:index')

@login_required
def zzi(request, products_pk):
    product = get_object_or_404(Products, pk=products_pk)
    if request.user in product.zzim.all():
        product.zzim.remove(request.user)
        user = product.user
        user.celsius -= 0.1
        user.celsius = round(user.celsius, 1)
        user.save()
    else:
        product.zzim.add(request.user)
        user = product.user
        user.celsius += 0.1
        user.celsius = round(user.celsius, 1)
        user.save()
    return redirect('products:detail', products_pk)

def sold_out(request, products_pk):
    product = get_object_or_404(Products, pk=products_pk)
    if request.user == product.user:
        if product.sold:
            product.sold = False
        else:
            product.sold = True
        product.save()
    return redirect('products:detail', products_pk)

# 검색 기능 + 검색어 저장
def search(request):
    search = request.GET.get("search")
    search_found = Popularsearch.objects.filter(terms=search)
    search_all = Popularsearch.objects.order_by('-searchCount')[:3]

    if search:
        # index에 검색 결과 뿌려주는 쿼리셋 저장
        search_result = Products.objects.filter(title__contains=search)
    
    # 사용자로부터 입력받은 검색어가 이미 있다면 searchCount += 1
    if search_found:
        search_exist = Popularsearch.objects.get(terms=search)
        search_exist.searchCount += 1
        search_exist.save()
    else:
        # 사용자로부터 입력받은 검색어를 DB에 저장
        Popularsearch.objects.create(terms=search)

    context = {
        'search_result': search_result,
        'search_all': search_all,
        'search': search,
    }
    return render(request, 'products/index.html', context)

products/templates/products/detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">

    <!-- 상품 이미지 -->
    <div class="d-flex justify-content-start my-5 mb-2">
      <div class="img_large d-flex align-items-center justify-content-center" style="text-align:center;display:table; width:400px; height:400x;">
        <img src="{{ products.original_image.url }}" alt="{{ products.original_image }}" style="width:400px; max-height:400px;" class="rounded">
        {% if products.sold %}
          <div style="position: absolute;width:100%; font-size:50px;text-align:center;">
            <img class='bg-dark bg-opacity-25 rounded' src="../../../static/images/soldout.png" alt="" style="max-width:400px; max-height:400px;">
          </div>
        {% endif %}
      </div>

      <!-- 상품 정보 -->
      <div class="d-flex flex-column ms-5 mt-2" style="width:50rem">
        <h2 class="font">{{ products.title }}</h2>
        <div class="d-flex">
          <p class="mb-0">{{ products.created_at | date:'y.m.d'}}</p>
          <p class="mb-0 ms-3">조회수
            {{ products.hit }}</p>
        </div>
        <h3 class="fw-bold mt-2 text-success font">{{ products.price }}원</h5>
        <p class="fs-4 mt-2" style="width:48rem">{{ products.content }}</p>
      </div>
    </div>

    <!-- 프로필 -->
    <div class="ms-5">
      <span>
        {% if products.user.profile.image %}
          <a href="{% url 'accounts:profile' products.user.username %}" style="text-decoration:none" class="text-dark"><img src="{{ products.user.profile.image.url}}" class="rounded-circle" alt="" style="height: 60px; width:60px;"></a>
        {% else %}
          <a href="{% url 'accounts:profile' products.user.username %}" style="text-decoration:none" class="text-dark"><img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 60px; width:60px;"></a>
        {% endif %}
      </span>
      <span class="fw-bold ms-2">
        <a href="{% url 'accounts:profile' products.user.username %}" style="text-decoration:none" class="text-dark">{{ products.user.username }}</a>
        <span>
          매너온도
          {{ products.user.celsius}}℃
          {% if products.user.celsius < 36.5 %}
            <i class="bi bi-emoji-frown text-danger"></i>
          {% elif products.user.celsius == 36.5 %}
            <i class="bi bi-emoji-neutral"></i>
          {% else %}
            <i class="bi bi-emoji-smile text-primary"></i>
          {% endif %}
        </span>
      </span>
    </div>

    <!-- 작성자일 경우 -->
    {% if request.user == products.user %}
      <div class="d-flex justify-content-center">
        <a href="{% url 'products:index' %}" class="btn btn-primary">목록으로</a>
        <a href="{% url 'products:update' products.pk %}" class="btn btn-outline-success ms-3">수정</a>
        <a href="{% url 'products:delete' products.pk %}" class="btn btn-outline-danger ms-3">삭제</a>

        <a href="{% url 'products:sold_out' products.pk %}">
          {% if products.sold %}
            <button class="btn btn-outline-danger ms-3">판매중</button>
          {% else %}
            <button class="btn btn-outline-primary ms-3">거래 완료</button>
          {% endif %}
        </a>
      </div>
    {% endif %}

    <!-- 작성자가 아닌 경우 -->
    <div class="d-flex justify-content-center">
      {% if request.user != products.user %}
        <a href="{% url 'chats:first_send' products.user.pk %}" class="btn btn-outline-success mx-2">채팅하기</a>
      {% endif %}
    </div>

    <!-- 지도 -->
    <h3 class="my-4">거래장소</h3>
    <div id="map" style="width:100%;height:350px;"></div>
    <div class="text-center mt-3">
      <a href="{% url 'products:zzi' products.pk %}" style="text-decoration:none">
        {% if request.user in products.zzim.all %}
          <i class="bi bi-heart-fill text-danger"></i>
        {% else %}
          <i class="bi bi-heart text-danger"></i>
        {% endif %}
      </a>
      <span>{{ products.zzim.count }}명이 이 상품을 찜 했어요.</span>
    </div>

    <div id="x" style="display: none;">{{location.trade_locationx}}</div>
    <div id="y" style="display: none;">{{location.trade_locationy}}</div>
    <h3 class="my-3 mt-5">판매자가 파는 다른 상품</h3>
    <div class="row mb-5">
      {% for product in products.user.products_set.all %}
        {% if products.pk != product.pk %}
          <div class="col-3">
            <div class="card" style="width: 18rem;">
              <img src="{{ product.formatted_image.url }}" class="card-img-top" alt="...">
              <div class="card-body">
                <a href="{% url 'products:detail' product.pk %}" class="text-decoration-none text-dark">
                  <h5 class="card-title text-nowrap text-truncate">{{product.title}}</h5>
                </a>
                <p>{{ product.user.username }}</p>
                <p class="card-text ">{{ product.price }}원</p>
              </div>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>

  <style>
    .img_large {
      transform: scale(1);
      -webkit-transform: scale(1);
      -moz-transform: scale(1);
      -ms-transform: scale(1);
      -o-transform: scale(1);
      transition: all 0.3s ease-in-out;
    }

    .img_large:hover {
      transform: scale(2);
      -webkit-transform: scale(1.1);
      -moz-transform: scale(2);
      -ms-transform: scale(2);
      -o-transform: scale(2);
    }

    .font {
      font-family: 'Noto Sans KR', sans-serif;
    }
  </style>

  <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=bd6208aaf90cdbe7ef8ee1aa6baef997"></script>
  <script>
    const x = document
        .querySelector('#x')
        .innerText
      const y = document
          .querySelector('#y')
          .innerText
          console
          .log(x, y)
        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
          mapOption = {
            center: new kakao
              .maps
              .LatLng(y, x), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
          };
        var map = new kakao
          .maps
          .Map(mapContainer, mapOption);
        var markerPosition = new kakao
          .maps
          .LatLng(y, x);

        // 마커를 생성합니다
        var marker = new kakao
          .maps
          .Marker({position: markerPosition});

        // 마커가 지도 위에 표시되도록 설정합니다
        marker.setMap(map);
  </script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
{% endblock %}

products/templates/products/form.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% load static %} {% block content %}
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}
<div class="container">
    {% if request.resolver_match.url_name == 'create' %}
    <h1>중고 상품 등록</h1>
    {% else %}
    <h1>상품 정보 수정</h1>
    {% endif %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {% bootstrap_form productform %}
        <div id="map" style="width:100%;height:350px;"></div>
        <div id="clickLatlng"></div>
        <div id="x" style="display: none;">{{locationform.trade_locationx}}</div>
        <div id="y" style="display: none;">{{locationform.trade_locationy}}</div>
        <div class="d-flex justify-content-end m-3">
            {% bootstrap_button button_type="submit" content="OK" button_class="btn btn-outline-primary"%}</div>
    </form>

    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=bd6208aaf90cdbe7ef8ee1aa6baef997"></script>
    <script src="{% static 'js/product.js' %}"></script>
</div>
<script>
    window.setTimeout(function() {
    $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
    });
}, 1500);
</script>
{% endblock %}

products/templates/products/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block search %}
  <form action="{% url 'products:search' %}" class="d-flex" role="search" style="height:40px;">
    <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit" style="height:40px; width:80px;">검색</button>
  </form>
{% endblock %}
{% block content %}
  <!-- 배너 캐러셀 -->
  <div id="carouselExampleControls" class="carousel slide mt-3" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="../../../static/images/중고의집배너1.png" class="d-block w-100" alt="dummy-image1">
      </div>
      <div class="carousel-item">
        <img src="../../../static/images/중고의집배너2.png" class="d-block w-100" alt="dummy-image2">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <!-- 커뮤니티 이름 -->
  <h3 class="mt-5 fw-bold text-center text-success">중고거래 매물</h3>

  <!-- 인기검색어 -->
  {% if search %}
  <div class="block">
    <ul id="ticker">
        {% for search in search_all %}
        <a href="?search={{ search.terms }}" class="text-decoration-none text-black"><li class="text-center" ><span class="fw-bold">현재 인기 검색어 [{{ forloop.counter }}위]</span> {{ search.terms }} </li></a>
        {% endfor %}
    </ul>
  </div>
  {% else %}
  <div class="block">
      <ul id="ticker">
          {% for search in search_all %}
          <a href="search/?search={{ search.terms }}" class="text-decoration-none text-black"><li class="text-center" ><span class="fw-bold">현재 인기 검색어 [{{ forloop.counter }}위]</span> {{ search.terms }} </li></a>
          {% endfor %}
      </ul>
  </div>
  {% endif %}

  <!-- 커뮤니티 글쓰기 -->
  <div class='text-end mt-3'>
    <a class='btn btn-success btn-sm fw-bold' href="{% url 'products:create' %}">글쓰기
      <i class="bi bi-pencil"></i>
    </a>
  </div>

  <!-- 검색어 입력 시 검색어에 맞는 글만 출력 -->
  {% if search_result %}
    {% for search in search_result %}
      {% if search.user not in request.user.blocking.all %}
        <div class="row d-flex justify-content-between">
          <div class="card col-6 my-3" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4" style="position:relative;">
                  <a href="{% url 'products:detail' search.pk %}">
                    <img src="{{ search.formatted_image.url }}" alt="" class="card-img-top" style="height: 151px;">
                    {% if search.sold %}
                      <div style="position: absolute; width:100%; font-size:50px;text-align:center;" class="top-0 start-0" style="height:151.33px;">
                        <img class='bg-dark bg-opacity-25 rounded' src="../../../static/images/soldout.png" alt="" style="max-width:171.33px; max-height:151.33px;">
                      </div>
                    {% endif %}
                  </a>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">
                    <h5>
                      <span class="fw-bold">
                        <a href="{% url 'products:detail' search.pk %}" style="text-decoration:none" class="text-dark">[No.{{ forloop.revcounter }}]
                        </span>{{ search.title }}</a>
                    </h5>
                  </h5>
                  <p class="card-text fw-lighter text-muted">
                    <span class="mt-3">
                      {% if search.user.profile.image %}
                        <a class="text-dark" href="{% url 'accounts:profile' search.user.username %}" style="text-decoration:none">
                          <img src="{{ search.user.profile.image.url}}" class="rounded-circle" alt="" style="height: 40px; width:40px;">
                        </a>
                      {% else %}
                        <a class="text-dark" href="{% url 'accounts:profile' search.user.username %}" style="text-decoration:none">
                          <img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 40px; width:40px;">
                        </a>
                      {% endif %}
                    </span>
                    <a href="{% url 'accounts:profile' search.user.username %}" style="text-decoration:none" class="text-dark">{{ search.user.username }}</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
    <!-- 모든 글 출력 -->
  {% else %}
    <div class="row d-flex justify-content-between">
      {% for product in products %}
        {% if product.user not in request.user.blocking.all %}
          <div class="card col-6 my-3" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4" style="position:relative;">
                <a href="{% url 'products:detail' product.pk %}">
                  <img src="{{ product.formatted_image.url }}" alt="" class="card-img-top" style="height: 151px;">
                  {% if product.sold %}
                    <div style="position: absolute; width:100%; font-size:50px;text-align:center;" class="top-0 start-0 height: 151.33px;">
                      <img class='bg-dark bg-opacity-25 rounded' src="../../../static/images/soldout.png" alt="" style="max-width:171.33px; max-height:151.33px;">
                    </div>
                  {% endif %}
                </a>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">
                    <h5>
                      <span class="fw-bold">
                        <a href="{% url 'products:detail' product.pk %}" style="text-decoration:none" class="text-dark">[No.{{ forloop.revcounter }}]
                        </span>{{ product.title }}</a>
                    </h5>
                  </h5>
                  <p class="card-text fw-lighter text-muted">
                    <span class="mt-3">
                      {% if product.user.profile.image %}
                        <a class="text-dark" href="{% url 'accounts:profile' product.user.username %}" style="text-decoration:none">
                          <img src="{{ product.user.profile.image.url}}" class="rounded-circle" alt="" style="height: 40px; width:40px;">
                        </a>
                      {% else %}
                        <a class="text-dark" href="{% url 'accounts:profile' product.user.username %}" style="text-decoration:none">
                          <img src="../../../static/images/hmm.png" class="rounded-circle" alt="" style="height: 40px; width:40px;">
                        </a>
                      {% endif %}
                    </span>
                    <a href="{% url 'accounts:profile' product.user.username %}" style="text-decoration:none" class="text-dark">{{ product.user.username }}</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>

  {% endif %}

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
  <script type='text/javascript' src="{% static 'js/search_view.js' %}"></script>
  <link rel="stylesheet" href="{% static './css/search_view.css' %}">
{% endblock content %}